#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  notorius28
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'radarr-folder-organizer'
        image: 'rubasace/radarr-folder-organizer'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: Create Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
          - /opt/appdata/{{pgrole}}/logs

    - name: Create Files
      file: 'path={{item}} state=touch mode=0755 owner=1000 group=1000'
      with_items:
          - /opt/appdata/{{pgrole}}/Config.txt

    # LABELS ######################################################################

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/logs:/logs'
          - '/opt/appdata/{{pgrole}}/Config.txt:/Config.txt'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          DELAY: '15m'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
